print('hello, dude!')
name = input('what is ur name?    ')
print('nice to meet u,', name)
year=int(input('what year were u born in?    '))
print('oh,',year,'was great!')
age=int(2020-year)
print('u are already',age,'!')
print('there are', len(str(name)),'letters in ur name ')
